version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: dojo-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/mdb:/data/db

  postgres:
    image: postgres:16
    container_name: dojo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dojo
      POSTGRES_PASSWORD: dojo
      POSTGRES_DB: dojo
    ports:
      - "5432:5432"
    volumes:
      - ./data/pdb:/var/lib/postgresql/data

